### ISSUE TITLE
[Question] Obtain coverage for non-crashing inputs

### ISSUE THREAD

**Issue by rc0r** [bshastry/afl-sancov#1]
Hi @bshastry,

is there a way to collect coverage statistics for not only the crashes but the complete corpus/queue generated by afl?

Or in other words: Can **afl-sancov** be used to automate the process of running `sancov`/`pysancov` on all afl queue items and aggregate the results in one report?

This overall report could then be used to characterize the overall fuzzing process. One such example use case would be using the report data to decide if/when/whether fuzzing runs (have) finish(ed) or if the fuzzers hit some road block...

**Comment by bshastry** [comment]
Hi @rc0r 

> is there a way to collect coverage statistics for not only the crashes but the complete corpus/queue generated by afl?

You can use v1.0 to collect queue coverage stats with something like this:

``` bash
$ afl-sancov -e "cat AFL_FILE | ./main" -d ./afl-out --sancov-path=/usr/bin/sancov-3.8 --pysancov-path=/usr/local/bin/pysancov --llvm-sym-path=/usr/bin/llvm-symbolizer-3.8 --bin-path=path_to_main
```

If all goes well, this should write all (positive) coverage to a file called `./afl-out/sancov/pos-cov`. Is this what you want? JSON support would've been nice I suppose but at the moment it just dumps a bunch of covered source lines in one single file.

**Comment by rc0r** [comment]
Thanks, that's basically what I tried but **afl-sancov** just exited with:

```
[*] --crash-dir missing or not a dir
```

**Comment by bshastry** [comment]
Looks like you are using v1.1 (where `--crash-dir` was introduced). Could you please try this with v1.0 and let me know how it goes?

Thanks a ton!

P.S. I should add that supporting queue coverage seemed unnecessary overhead given afl-cov does this already. So I deprecated this feature to give more attention to the seemingly novel crash coverage and differential crash coverage. Also, the next release of Orthrus will subsume most of the functionality of the present version of `afl-sancov` (Already available in Orthrus' `dev` branch)...

**Comment by rc0r** [comment]
Sorry, I totally forgot about this one. `afl-cov` was exactly what I was looking for. Thanks for your suggestions.
